### PR TITLE
Fix Error: Invalid value for <path> attribute d="..."

### PR DESCRIPTION
**Pull request by ggregoire**

### CODE REVIEW

**Comment by crisbeto** [comment]
What are the cases in which it throws this error?

**Comment by ggregoire** [comment]
Hello,

I have those errors when I load `angular-i18n/angular-locale_fr-fr.js` in my app...

I found a closed issue about it (https://github.com/crisbeto/angular-svg-round-progressbar/issues/10).

**Comment by crisbeto** [comment]
Strange, I'm not sure that adding the `ng-attr-` is the real fix. Maybe the numbers are being passed along with a comma instead of a decimal and thus are interpreted as strings? I'll try to reproduce it locally.

**Comment by crisbeto** [comment]
@ggregoire I've pushed a fix for this in 1ebd58ee88450a0cb4563fe0797a7c1383bde1dd, can you give it a try?

**Comment by ggregoire** [comment]
Ok I'll try your fix at work tomorrow. Thank you! :)

**Comment by ggregoire** [comment]
Ok that perfectly works! Thank you

**Pull request closed without merging**
